### ISSUE TITLE
unsquashfs doesn't exit if partition fills up during the process

### ISSUE THREAD

**Issue by SantoshKumar4** [plougher/squashfs-tools#49]
$ unsquashfs -li file.squashfs
Parallel unsquashfs: Using 2 processors
2 inodes (24447 blocks) to write

drwxr-xr-x root/root                67 2018-05-10 15:48 squashfs-root
-rw-r--r-- root/root                45 2018-05-10 15:48 squashfs-root/file.md5
-rw-r--r-- root/root        3204133376 2018-05-10 15:48 squashfs-root/file.raw

**Write on output file failed because No space left on device
writer: failed to write data block 15591**

**_pstack shows me this:_**
```
$ pstack 31170
Thread 7 (Thread 0x7f73b8815700 (LWP 31171)):
#0  0x00007f73b9759945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040375b in queue_get ()
#2  0x00000000004046d4 in reader ()
#3  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f73b8014700 (LWP 31172)):
#0  0x00007f73b9759945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040375b in queue_get ()
#2  0x0000000000407089 in writer ()
#3  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f73b7813700 (LWP 31173)):
#0  0x00007f73b975ce4d in nanosleep () from /lib64/libpthread.so.0
#1  0x0000000000407b29 in progress_thread ()
#2  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f73b7012700 (LWP 31174)):
#0  0x00007f73b884c3fa in sigwaitinfo () from /lib64/libc.so.6
#1  0x000000000040c68c in info_thrd ()
#2  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f73b6811700 (LWP 31175)):
#0  0x00007f73b9759945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040375b in queue_get ()
#2  0x00000000004072bd in inflator ()
#3  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f73b6010700 (LWP 31176)):
#0  0x00007f73b9759945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040375b in queue_get ()
#2  0x00000000004072bd in inflator ()
#3  0x00007f73b9755e25 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f73b890e34d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f73b9b7d740 (LWP 31170)):
#0  0x00007f73b9759945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000004041c3 in cache_get ()
#2  0x00000000004050d4 in write_file ()
#3  0x000000000040544b in create_inode ()
#4  0x0000000000405e91 in dir_scan ()
#5  0x00000000004028b5 in main ()


```

Can it exit with failure?

Thanks

**Comment by plougher** [comment]
Failure to output to the destination filesystem is now treated as a fatal error, and Unsquashfs will abort with an error exit code.
